#!/usr/bin/env python3
from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


BITMAP_WIDTH = 9
BITMAP_HEIGHT = 16
RENDER_WIDTH = 9
RENDER_HEIGHT = 16
ADVANCE_X = 8
FONT_SIZE = 14


def candidate_fonts() -> list[Path]:
    env_path = os.environ.get("JABULOS_FONT_PATH")
    candidates = []
    if env_path:
        candidates.append(Path(env_path))

    candidates.extend(
        [
            Path("/mnt/c/Windows/Fonts/consola.ttf"),
            Path("/mnt/c/Windows/Fonts/SegUIVar.ttf"),
            Path("/mnt/c/Windows/Fonts/segoeui.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"),
            Path("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
        ]
    )
    return candidates


def load_font() -> tuple[ImageFont.FreeTypeFont, Path]:
    for candidate in candidate_fonts():
        if candidate.exists():
            return ImageFont.truetype(str(candidate), FONT_SIZE), candidate
    raise FileNotFoundError("No usable Segoe UI Variable or fallback font was found")


def font_vertical_offset(font: ImageFont.FreeTypeFont) -> int:
    min_top = 0
    max_bottom = 0

    for codepoint in range(32, 127):
        bbox = font.getbbox(chr(codepoint))
        min_top = min(min_top, bbox[1])
        max_bottom = max(max_bottom, bbox[3])

    total_height = max_bottom - min_top
    return ((BITMAP_HEIGHT - total_height) // 2) - min_top


def font_horizontal_offset(font: ImageFont.FreeTypeFont) -> int:
    min_left = 0
    max_right = 0

    for codepoint in range(32, 127):
        bbox = font.getbbox(chr(codepoint))
        min_left = min(min_left, bbox[0])
        max_right = max(max_right, bbox[2])

    total_width = max_right - min_left
    return ((BITMAP_WIDTH - total_width) // 2) - min_left


def rasterize(font: ImageFont.FreeTypeFont, ch: str, origin_x: int, baseline_y: int) -> list[list[int]]:
    image = Image.new("L", (BITMAP_WIDTH, BITMAP_HEIGHT), 0)
    draw = ImageDraw.Draw(image)

    if ch != " ":
        draw.text((origin_x, baseline_y), ch, font=font, fill=255)

    rows = []
    for py in range(BITMAP_HEIGHT):
        row = []
        for px in range(BITMAP_WIDTH):
            row.append(image.getpixel((px, py)))
        rows.append(row)
    return rows


def emit_header(out_path: Path, font_path: Path, glyph_rows: list[list[list[int]]]) -> None:
    lines = [
        "/* Auto-generated by tools/generate_font.py. */",
        f"/* Source font: {font_path} */",
        "#ifndef UI_FONT_H",
        "#define UI_FONT_H",
        "",
        "#include \"jabulos.h\"",
        "",
        f"#define UI_FONT_BITMAP_WIDTH {BITMAP_WIDTH}u",
        f"#define UI_FONT_BITMAP_HEIGHT {BITMAP_HEIGHT}u",
        f"#define UI_FONT_RENDER_WIDTH {RENDER_WIDTH}u",
        f"#define UI_FONT_RENDER_HEIGHT {RENDER_HEIGHT}u",
        f"#define UI_FONT_ADVANCE_X {ADVANCE_X}u",
        "",
        f"static const u8 ui_font_alpha[128][{BITMAP_HEIGHT}][{BITMAP_WIDTH}] = {{",
    ]

    for codepoint in range(128):
        rows = ", ".join(
            "{" + ", ".join(f"{value}" for value in row) + "}"
            for row in glyph_rows[codepoint]
        )
        label = repr(chr(codepoint)) if 32 <= codepoint < 127 else f"0x{codepoint:02X}"
        lines.append(f"    [{codepoint}] = {{{rows}}}, /* {label} */")

    lines.extend(
        [
            "};",
            "",
            "#endif",
        ]
    )
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_font.py <output-header>", file=sys.stderr)
        return 1

    out_path = Path(sys.argv[1])
    out_path.parent.mkdir(parents=True, exist_ok=True)

    font, font_path = load_font()
    origin_x = font_horizontal_offset(font)
    baseline_y = font_vertical_offset(font)
    glyph_rows = [[[0] * BITMAP_WIDTH for _ in range(BITMAP_HEIGHT)] for _ in range(128)]

    for codepoint in range(32, 127):
        glyph_rows[codepoint] = rasterize(font, chr(codepoint), origin_x, baseline_y)

    glyph_rows[ord("?")] = rasterize(font, "?", origin_x, baseline_y)
    emit_header(out_path, font_path, glyph_rows)
    print(f"[jabulOS Aero] Generated font header from {font_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
